name: Build to pyinstaller

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**/.github'
env:
  UPLOAD_DIR: false
  UPLOAD_RELEASE: true

jobs:
  build:
    runs-on: ubuntu-20.04 
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Download pyinstaller
      env: 
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential bzip2 gawk gettext git patch unzip htop wget curl python3  -y
        sudo -E pip3 install pyinstaller
    - name: Build:
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        
        
